Revert of Give user ability to file a feedback report from the display error notification. (patchset #5 id:80001 of https://codereview.chromium.org/1636153002/ )
Reason for revert:
Missing include causing compile failure in win64:

FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\4087e065abebdca6dbd0caca2910c6718d2ec67f\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/ui/display/types/types/display_snapshot.obj.rsp /c ../../ui/display/types/display_snapshot.cc /Foobj/ui/display/types/types/display_snapshot.obj /Fdobj/ui/display/types/types_cc.pdb
e:\b\build\slave\win_x64_gn\build\src\ui\display\types\display_snapshot.cc(46) : error C2039: 'min' : is not a member of 'std'
e:\b\build\slave\win_x64_gn\build\src\ui\display\types\display_snapshot.cc(46) : error C3861: 'min': identifier not found
ninja: build stopped: subcommand failed.

Original issue's description:
> Give user ability to file a feedback report from the display error notification.
>
> Make the display error notification clickable and starts the feedback app on click.
> We log the available displays IDs and EDIDs.
>
> BUG=570380
> TEST=manually
>
> Committed: https://crrev.com/965f9b3c3a245b52b8720cecbd598576853ba719
> Cr-Commit-Position: refs/heads/master@{#373895}

TBR=spang@chromium.org,erg@chromium.org,kenrb@chromium.org,oshima@chromium.org,afakhry@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=570380

Review URL: https://codereview.chromium.org/1671223002

Cr-Commit-Position: refs/heads/master@{#373910}