MediaStreamRecorder: enable in Android (including linking libwebm)
This follows a conversation in the Intent-To-Ship [1].

The added code means:
- third_party/libwebm
- media::WebmMuxer
- content::AudioTrackRecorder
- content::VideoTrackRecorder
- content::MediaRecorderHandler.

third_party/libwebm size: 10154B

Increase in ChromePublic-unsigned.apk:
54673026 - 54651438 = 21588B ~= 21KB

----- Note:
Modified code in webm_muxer.cc due to complaint from
arm-linux-androideabi-4.9:
../../media/capture/webm_muxer.cc:49:76: error: array subscript is above array bounds [-Werror=array-bounds]
            kOpusVorbisChannelMap[params.channels() - 1], params.channels());
------

BUG=262211, 561068

TEST=Same as for desktop platform:
https://rawgit.com/Miguelao/demos/master/mediarecorder.html
Results of running it can be found under [2] and [3]

[1] https://groups.google.com/a/chromium.org/d/msg/blink-dev/76HB0BIxk_o/LtZYZWvVBQAJ
[2] https://drive.google.com/file/d/0B82Jhdx0kSTVS3E4bFZwZUxSSTQ/view?usp=sharing
[3] https://drive.google.com/file/d/0B82Jhdx0kSTVM3lfR2N0RFlwNzg/view?usp=sharing

Review URL: https://codereview.chromium.org/1486623004

Cr-Commit-Position: refs/heads/master@{#362536}