Revert of Created the dialog offering the user to merge their account data or keep it (patchset #12 id:220001 of https://codereview.chromium.org/1698043006/ )
Reason for revert:
Causes the downstream test failure http://crbug.com/590238 in "testConsumerSignin", blocking the Clank roll.

junit.framework.AssertionFailedError: Could not locate the fragment with tag 'account_picker_dialog_tag'

BUG=590238

Original issue's description:
> (formerly: Created the dialog offering the user to merge their account data or keep it)
>
> This CL contains two changes to the Switching Sync Account flows.
> - It adds the ability to switch sync accounts, presenting a dialog offering the user to merge their account data or keep it separate.
> - It upgrades the account signin from preferences from using the ChooseAccountFragment to using the AccountSigninView (formerly the AccountFirstRunView).
>
> In addition it:
> - Renames AccountFirstRunView to AccountSigninView (since it is not used only in the first run).
> - Renames functions in the AccountSigninView from using SignIn to Signin.
>
> The following user actions were modified:
> - Signin_AddAccountToDevice
> - Signin_ImportDataPrompt_Cancel
> - Signin_ImportDataPrompt_DontImport
> - Signin_ImportDataPrompt_ImportData
> - Signin_Signin_FromSettings
> - Signin_Undo_Signin
>
> BUG=557786
>
> Committed: https://crrev.com/bd705aeab0594a1790478e335edee728f32fb026
> Cr-Commit-Position: refs/heads/master@{#377769}

TBR=maybelle@chromium.org,bauerb@chromium.org,yusufo@chromium.org,newt@chromium.org,gogerald@chromium.org,x-a-x@hotmail.co.th,ewald@chromium.org,skym@chromium.org,peconn@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=557786

Review URL: https://codereview.chromium.org/1745563002

Cr-Commit-Position: refs/heads/master@{#377978}