Revert of [Android] Get package_info by using apk_under_test package. (patchset #1 id:1 of https://codereview.chromium.org/1893693002/ )
Reason for revert:
Breaks the MogoTests due to this error.

AttributeError: 'NoneType' object has no attribute 'GetPackageName'

Original issue's description:
> [Android] Get package_info by using apk_under_test package.
>
> Currently, the package_info used by the test apk is looked up by
> by looking at the test_apk package in the list of package_infos.
> Instead, we can just look at the package entries in the list
> of package_infos and compare it to the package of the apk_under_test.
>
> This makes things much nicer, when for instance you have multiple
> test apks targeting the same package.
>
> BUG=
>
> Committed: https://crrev.com/f6c372aea4a4c79598b9414a9049b7ac5f659f2e
> Cr-Commit-Position: refs/heads/master@{#387943}

TBR=agrieve@chromium.org,rnephew@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/1900873002

Cr-Commit-Position: refs/heads/master@{#387996}