Check Android API level when using usb.UsbDevice.getManufacturerName
android.hardware.usb.UsbDevice.getManufacturerName was added in API
level 21. This patch added code to check the API level to avoid
java.lang.NoSuchMethodError when testing pervious Android versions.

BUG=604634

Review URL: https://codereview.chromium.org/1898043003

Cr-Commit-Position: refs/heads/master@{#388294}