Revert of Introduce components/display_compositor (patchset #21 id:390001 of https://codereview.chromium.org/1902463002/ )
Reason for revert:
Broke Windows x64 build.
c:\b\build\slave\win_x64_builder__dbg_\build\src\components\display_compositor\buffer_queue_unittest.cc(142): error C2220: warning treated as error - no 'object' file generated
c:\b\build\slave\win_x64_builder__dbg_\build\src\components\display_compositor\buffer_queue_unittest.cc(142): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data

https://build.chromium.org/p/chromium.win/builders/Win%20x64%20Builder%20%28dbg%29/builds/20984/steps/compile/logs/stdio

Original issue's description:
> Introduce components/display_compositor
>
> We would like to share BufferQueue, GLHelper and later other parts
> of content/browser/compositor in Mus. This CL introduces a new
> display_compositor component and moves BufferQueue, GLHelper and
> friends to components/display_compositor.
>
> BUG=601867
> TBR=ben@chromium.org
> CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel

TBR=piman@chromium.org,sky@chromium.org,xhwang@chromium.org,ben@chromium.org,fsamuel@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=601867

Review URL: https://codereview.chromium.org/1905863002

Cr-Commit-Position: refs/heads/master@{#388661}