Revert of Decouple browser-specific GPU IPC messages from GPU service IPCs (patchset #19 id:360001 of https://codereview.chromium.org/1711533002/ )
Reason for revert:
Regression: Win7 Tests (dbg)(1) browser_test failures

https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29

Sheriff-o-matic suspecting Change #198012 in Build 46233 for cause of Win7 Tests (dbg)(1) browser_test failures:

https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/46233
In step 91. browser_tests
failures:
    DevToolsPixelOutputTests.TestLatencyInfoInstrumentation
    DevToolsPixelOutputTests.TestScreenshotRecording

Logs:

https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/46233/steps/browser_tests%20on%20Windows-7-SP1/logs/DevToolsPixelOutputTests.TestLatencyInfoInstrumentation
https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/46233/steps/browser_tests%20on%20Windows-7-SP1/logs/DevToolsPixelOutputTests.TestScreenshotRecording

[ RUN      ] DevToolsPixelOutputTests.TestLatencyInfoInstrumentation
[2840:5856:0224/124138:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Could not create D3D11 device.
[2840:5856:0224/124138:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type
[2840:5856:0224/124139:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Renderer does not support PS 3.0.aborting!
[2840:5856:0224/124139:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D9 failed with error EGL_NOT_INITIALIZED
[2840:5856:0224/124139:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Could not create D3D11 device.
[2840:5856:0224/124139:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type
HTTP server started on http://127.0.0.1:58543...
sending server_data: {"host": "127.0.0.1", "port": 58543} (36 bytes)
[2840:5856:0224/124140:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Renderer does not support PS 3.0.aborting!
[2840:5856:0224/124140:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D9 failed with error EGL_NOT_INITIALIZED
[2840:5856:0224/124140:ERROR:gl_surface_win.cc(69)] GLSurfaceEGL::InitializeOneOff failed.
[2840:5856:0224/124140:ERROR:gpu_child_thread.cc(347)] Exiting GPU process due to errors during initialization
[2840:5856:0224/124140:FATAL:gpu_child_thread.cc(484)] Check failed: gpu_channel_manager_.
Backtrace:
	base::SysInfo::AmountOfVirtualMemory [0x100A8DB1+570092]
	base::SysInfo::AmountOfVirtualMemory [0x10100BCB+930054]
	content::ImageTransportFactory::ImageTransportFactory [0x176BA2F8+29889885]
	content::ImageTransportFactory::ImageTransportFactory [0x176B25D9+29857854]
	content::ImageTransportFactory::ImageTransportFactory [0x176B2118+29856637]
	content::ImageTransportFactory::ImageTransportFactory [0x176B23C6+29857323]
	content::ImageTransportFactory::ImageTransportFactory [0x176B141C+29853313]
	content::ImageTransportFactory::ImageTransportFactory [0x176BB492+29894391]
	IPC::Message::type [0x0FA2EA2B+166218]
	IPC::Message::type [0x0FA26F90+134831]
	IPC::Message::type [0x0FA26CE7+134150]
	IPC::Message::type [0x0FA2F6C2+169441]
	base::SysInfo::AmountOfVirtualMemory [0x1007C9BF+388858]
	base::SysInfo::AmountOfVirtualMemory [0x100AF147+595586]
	base::SysInfo::AmountOfVirtualMemory [0x1012E576+1116849]
	base::SysInfo::AmountOfVirtualMemory [0x1012BC74+1106351]
	base::SysInfo::AmountOfVirtualMemory [0x1012C43D+1108344]
	base::SysInfo::AmountOfVirtualMemory [0x10137E44+1155967]
	base::SysInfo::AmountOfVirtualMemory [0x10139E62+1164189]
	base::SysInfo::AmountOfVirtualMemory [0x10139DBC+1164023]
	base::SysInfo::AmountOfVirtualMemory [0x1012E1FF+1115962]
	base::SysInfo::AmountOfVirtualMemory [0x101C11C6+1718017]
	base::SysInfo::AmountOfVirtualMemory [0x1012E02D+1115496]
	content::ImageTransportFactory::ImageTransportFactory [0x176C0E20+29917317]
	content::ImageTransportFactory::ImageTransportFactory [0x15BEB179+1778654]
	content::ImageTransportFactory::ImageTransportFactory [0x15BEAF90+1778165]
	content::ImageTransportFactory::ImageTransportFactory [0x15BD4B70+1686997]
	content::LaunchTests [0x0849E65E+734]
	LaunchChromeTests [0x037F990D+125]
	main [0x01D5643E+110]
	__tmainCRTStartup [0x09B5DBE9+409] (f:\dd
ctools\crt\crtw32\dllstuff\crtexe.c:626)
	mainCRTStartup [0x09B5DD2D+13] (f:\dd
ctools\crt\crtw32\dllstuff\crtexe.c:466)
	BaseThreadInitThunk [0x767C337A+18]
	RtlInitializeExceptionChain [0x77D29882+99]
	RtlInitializeExceptionChain [0x77D29855+54]

=================

[ RUN      ] DevToolsPixelOutputTests.TestScreenshotRecording
[2512:3528:0224/124026:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Could not create D3D11 device.
[2512:3528:0224/124026:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type
[2512:3528:0224/124026:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Renderer does not support PS 3.0.aborting!
[2512:3528:0224/124026:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D9 failed with error EGL_NOT_INITIALIZED
[2512:3528:0224/124026:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Could not create D3D11 device.
[2512:3528:0224/124026:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D11 failed with error EGL_NOT_INITIALIZED, trying next display type
[2512:3528:0224/124026:ERROR:angle_platform_impl.cc(33)] ANGLE Display::initialize error 4: Renderer does not support PS 3.0.aborting!
[2512:3528:0224/124026:ERROR:gl_surface_egl.cc(586)] eglInitialize D3D9 failed with error EGL_NOT_INITIALIZED
[2512:3528:0224/124026:ERROR:gl_surface_win.cc(69)] GLSurfaceEGL::InitializeOneOff failed.
[2512:3528:0224/124026:ERROR:gpu_child_thread.cc(347)] Exiting GPU process due to errors during initialization
HTTP server started on http://127.0.0.1:51161...
sending server_data: {"host": "127.0.0.1", "port": 51161} (36 bytes)
[4708:1384:0224/124028:WARNING:message_queue.cc(38)] Leaking 2 ports in unreceived messages
[2512:3528:0224/124026:FATAL:gpu_child_thread.cc(484)] Check failed: gpu_channel_manager_.
Backtrace:
	base::SysInfo::AmountOfVirtualMemory [0x100A8DB1+570092]
	base::SysInfo::AmountOfVirtualMemory [0x10100BCB+930054]
	content::ImageTransportFactory::ImageTransportFactory [0x1778A2F8+29889885]
	content::ImageTransportFactory::ImageTransportFactory [0x177825D9+29857854]
	content::ImageTransportFactory::ImageTransportFactory [0x17782118+29856637]
	content::ImageTransportFactory::ImageTransportFactory [0x177823C6+29857323]
	content::ImageTransportFactory::ImageTransportFactory [0x1778141C+29853313]
	content::ImageTransportFactory::ImageTransportFactory [0x1778B492+29894391]
	IPC::Message::type [0x0FAFEA2B+166218]
	IPC::Message::type [0x0FAF6F90+134831]
	IPC::Message::type [0x0FAF6CE7+134150]
	IPC::Message::type [0x0FAFF6C2+169441]
	base::SysInfo::AmountOfVirtualMemory [0x1007C9BF+388858]
	base::SysInfo::AmountOfVirtualMemory [0x100AF147+595586]
	base::SysInfo::AmountOfVirtualMemory [0x1012E576+1116849]
	base::SysInfo::AmountOfVirtualMemory [0x1012BC74+1106351]
	base::SysInfo::AmountOfVirtualMemory [0x1012C43D+1108344]
	base::SysInfo::AmountOfVirtualMemory [0x10137E44+1155967]
	base::SysInfo::AmountOfVirtualMemory [0x10139E62+1164189]
	base::SysInfo::AmountOfVirtualMemory [0x10139DBC+1164023]
	base::SysInfo::AmountOfVirtualMemory [0x1012E1FF+1115962]
	base::SysInfo::AmountOfVirtualMemory [0x101C11C6+1718017]
	base::SysInfo::AmountOfVirtualMemory [0x1012E02D+1115496]
	content::ImageTransportFactory::ImageTransportFactory [0x17790E20+29917317]
	content::ImageTransportFactory::ImageTransportFactory [0x15CBB179+1778654]
	content::ImageTransportFactory::ImageTransportFactory [0x15CBAF90+1778165]
	content::ImageTransportFactory::ImageTransportFactory [0x15CA4B70+1686997]
	content::LaunchTests [0x0849E65E+734]
	LaunchChromeTests [0x037F990D+125]
	main [0x01D5643E+110]
	__tmainCRTStartup [0x09B5DBE9+409] (f:\dd
ctools\crt\crtw32\dllstuff\crtexe.c:626)
	mainCRTStartup [0x09B5DD2D+13] (f:\dd
ctools\crt\crtw32\dllstuff\crtexe.c:466)
	BaseThreadInitThunk [0x76C2337A+18]
	RtlInitializeExceptionChain [0x778692B2+99]
	RtlInitializeExceptionChain [0x77869285+54]

[3768:3420:0224/124033:ERROR:singleton_hwnd.cc(34)] Cannot create windows on non-UI thread!
[4708:1384:0224/124034:ERROR:CONSOLE(72)] "Uncaught TypeError: Cannot read property 'addExtensions' of undefined", source:  (72)
[4708:1384:0224/124035:INFO:CONSOLE(1)] "DONE:performActionsInPage.1", source:  (1)
c:uild\slave\win_builder__dbg_uild\src\chromerowser\devtools\devtools_sanity_browsertest.cc(124): error: Value of: result
  Actual: "[FAILED] Expected: 'true', but was 'false'"
Expected: "[OK]"
[4708:1384:0224/124038:WARNING:url_request_context_getter.cc(42)] URLRequestContextGetter leaking due to no owning thread.
[  FAILED  ] DevToolsPixelOutputTests.TestScreenshotRecording, where TypeParam =  and GetParam() =  (12746 ms)

Original issue's description:
> Decouple browser-specific GPU IPC messages from GPU service IPCs
>
> We would like Mus to reuse GPU service IPC messages. However,
> browser-specific<=>gpu messages don't necessarily
> make sense in Mus+Ash. This CL decouples browser messages
> from Gpu channel messages in the following ways:
>
> 1. Browser channel messages are moved to a gpu_host_messages.h file.
>
> 2. Browser channel message handling is moved entirely to GpuChildThread.
>
> 3. GpuChannelManager is decoupled from GpuChildThread by making
> GpuChildThread a GpuChannelManagerDelegate.
>
> The intent here is for Mus to implement an alternative
> GpuChannelManagerDelegate.
>
> BUG=586374
>
> Committed: https://crrev.com/6904b50eb105956b954279f9632f680251e41aa7
> Cr-Commit-Position: refs/heads/master@{#377341}

TBR=sievers@chromium.org,piman@chromium.org,markdittmer@chromium.org,tsepez@chromium.org,fsamuel@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=586374

Review URL: https://codereview.chromium.org/1730023004

Cr-Commit-Position: refs/heads/master@{#377431}