Revert of Change scoped_ptr to std::unique_ptr in //net/base. (patchset #2 id:20001 of https://codereview.chromium.org/1894743002/ )
Reason for revert:
broke ios bots: https://build.chromium.org/p/chromium.mac/builders/iOS_Device_%28ninja%29/builds/49255/steps/compile/logs/stdio

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/net/tools/dump_cache/dump_cache.dump_files.arm64.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=264915-1 -DUSE_LIBJPEG_TURBO=1 -DFIELDTRIAL_TESTING_ENABLED -DDISABLE_FTP_SUPPORT=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DUSE_SYSTEM_LIBXML -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNS_BLOCK_ASSERTIONS=1 -D_FORTIFY_SOURCE=2 -Igen -I/Applications/Xcode7.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/usr/include/libxml2 -I../.. -I../../testing/gtest/include -I../../testing/gmock/include -isysroot /Applications/Xcode7.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -Os -gdwarf-2 -fvisibility=hidden -Werror -miphoneos-version-min=9.0 -arch arm64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -Xclang -load -Xclang /b/build/slave/iOS_Device__ninja_/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -fcolor-diagnostics  -c ../../net/tools/dump_cache/dump_files.cc -o obj/net/tools/dump_cache/dump_cache.dump_files.arm64.o
../../net/tools/dump_cache/dump_files.cc:83:3: error: no template named 'scoped_ptr'; did you mean 'scoped_refptr'?
  scoped_ptr<int32_t[]> buffer(new int32_t[length]);
  ^~~~~~~~~~
  scoped_refptr

Original issue's description:
> Change scoped_ptr to std::unique_ptr in //net/base.
>
> R=eroman@chromium.org, gavinp@chromium.org
> TBR=brettw
> BUG=554298
>
> Committed: https://crrev.com/42edb859e1917c96b988fa2f4e204de63aeb18ae
> Cr-Commit-Position: refs/heads/master@{#387784}

TBR=eroman@chromium.org,gavinp@chromium.org,brettw@chromium.org,danakj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=554298

Review URL: https://codereview.chromium.org/1890383002

Cr-Commit-Position: refs/heads/master@{#387788}