Revert of content: build fix about ContentDecryptorDelegate (patchset #1 id:1 of https://codereview.chromium.org/1575833002/ )
Reason for revert:
This issue is known in crbug.com/506663 and we want to fix c++ spec and clang rather than making chromium code silly.
Nico asked to revert it.

Original issue's description:
> content: build fix about ContentDecryptorDelegate
>
> clang complains it doesn't initialize const member, so this CL calls the
> default constructor explicitly.
>
> ../../content/renderer/pepper/content_decryptor_delegate.cc:1070:32: error: default initialization of an object of const type 'const Decryptor::AudioFrames' (aka 'const list<scoped_refptr<media::AudioBuffer> >') without a user-provided default constructor
>   const Decryptor::AudioFrames empty_frames;
>                                ^
>                                            {}
> ../../content/renderer/pepper/content_decryptor_delegate.cc:1282:41: error: default initialization of an object of const type 'const media::Decryptor::AudioFrames' (aka 'const list<scoped_refptr<media::AudioBuffer> >') without a user-provided default constructor
>     const media::Decryptor::AudioFrames empty_frames;
>                                         ^
>                                                     {}
> 2 errors generated.
>
> Committed: https://crrev.com/c8c01a1673e799bfdc37b266acf68118cd759b08
> Cr-Commit-Position: refs/heads/master@{#368626}

TBR=bbudge@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.

Review URL: https://codereview.chromium.org/1577323005

Cr-Commit-Position: refs/heads/master@{#369132}